name: Deploy

on:
  release:
    types: [published]

jobs:
  tests:
    name: Test / ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - Ubuntu
          - macOS
          - Windows
        python-version:
          - 3.9
          - 3.8
          - 3.7
          - 3.6
    env:
      PY_COLORS: 1
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: python -m pip install tox-gh-actions
      - name: Prepare test environment
        run: tox --notest
      - name: Test
        run: tox

  publish:
    needs: tests
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install -U setuptools wheel
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.2.2
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.2.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
